services:
  - type: web
    name: pedal-backend
    env: go
    plan: free
    region: oregon
    buildCommand: go build -o server .
    startCommand: ./server
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
